// <auto-generated />
using System;
using CreditosChevrolet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditosChevrolet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125020945_AddPlazoMesesToRespuesta")]
    partial class AddPlazoMesesToRespuesta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditosChevrolet.Models.NotificacionAsesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsesorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudCreditoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudCreditoId");

                    b.ToTable("NotificacionesAsesor");
                });

            modelBuilder.Entity("CreditosChevrolet.Models.RespuestaCreditoFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoAprobado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlazoMeses")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudCreditoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tasa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudCreditoId");

                    b.ToTable("RespuestasCredito");
                });

            modelBuilder.Entity("CreditosChevrolet.Models.SolicitudCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsesorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinancieraId")
                        .HasColumnType("int");

                    b.Property<int?>("MinutosReintento")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique();

                    b.ToTable("SolicitudesCredito");
                });

            modelBuilder.Entity("CreditosChevrolet.Models.NotificacionAsesor", b =>
                {
                    b.HasOne("CreditosChevrolet.Models.SolicitudCredito", "SolicitudCredito")
                        .WithMany()
                        .HasForeignKey("SolicitudCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudCredito");
                });

            modelBuilder.Entity("CreditosChevrolet.Models.RespuestaCreditoFinanciera", b =>
                {
                    b.HasOne("CreditosChevrolet.Models.SolicitudCredito", "SolicitudCredito")
                        .WithMany("Respuestas")
                        .HasForeignKey("SolicitudCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudCredito");
                });

            modelBuilder.Entity("CreditosChevrolet.Models.SolicitudCredito", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
